name: Ejecutar Notebooks y Analisis Python

# El workflow se ejecuta manualmente, y cada vez que haces push a la rama principal.
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ejecutar_analisis:
    # Ejecuta el trabajo en un entorno Linux (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Obtener el código de tu repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # Paso 2: Configurar el entorno de Python
      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # Puedes especificar una versión diferente si la necesitas

      # Paso 3: Instalar librerías de Python (asegúrate de tener un archivo requirements.txt)
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      # Paso 4: Instalar las librerías necesarias para ejecutar Jupyter Notebooks
      - name: Instalar librerías de Notebook
        run: pip install jupyter nbconvert

      # Paso 5: (OPCIONAL) Ejecutar el Notebook de Jupyter
      # Esto ejecuta un archivo .ipynb y lo guarda como un HTML o un nuevo .ipynb
      - name: Ejecutar y exportar Notebook
        # Reemplaza 'nombre_de_tu_notebook.ipynb' por el nombre real de tu archivo
        run: jupyter nbconvert --to html --execute tu_notebook_de_analisis.ipynb
        
      # Paso 6: (OPCIONAL) Mostrar un mensaje de éxito
      - name: Reporte de éxito
        run: echo "El análisis y la exportación del notebook se completaron."
